"""Initial migrations

Revision ID: bcc61227502f
Revises: 
Create Date: 2026-07-22 16:07:51.376741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcc61227502f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('connector_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_source_revision', sa.String(length=255), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connectors'))
    )
    op.create_index(op.f('ix_connectors_status'), 'connectors', ['status'], unique=False)
    op.create_table('file_metadata',
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('raw_object_key', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_file_metadata_connector_id_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_metadata')),
    sa.UniqueConstraint('connector_id', 'external_id', name='uq_file_metadata_connector_external_id')
    )
    op.create_index(op.f('ix_file_metadata_connector_id'), 'file_metadata', ['connector_id'], unique=False)
    op.create_table('canonical_documents',
    sa.Column('file_metadata_id', sa.Uuid(), nullable=False),
    sa.Column('document_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('headings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_metadata_id'], ['file_metadata.id'], name=op.f('fk_canonical_documents_file_metadata_id_file_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_documents')),
    sa.UniqueConstraint('document_key', name=op.f('uq_canonical_documents_document_key')),
    sa.UniqueConstraint('file_metadata_id', name=op.f('uq_canonical_documents_file_metadata_id'))
    )
    op.create_index(op.f('ix_canonical_documents_content_hash'), 'canonical_documents', ['content_hash'], unique=False)
    op.create_table('document_chunks',
    sa.Column('canonical_document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_key', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('heading_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunking_strategy', sa.String(length=100), nullable=False),
    sa.Column('chunking_version', sa.String(length=100), nullable=False),
    sa.Column('index_status', sa.String(length=30), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_document_id'], ['canonical_documents.id'], name=op.f('fk_document_chunks_canonical_document_id_canonical_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('canonical_document_id', 'chunk_index', 'chunking_version', name='uq_document_chunks_document_index_version'),
    sa.UniqueConstraint('chunk_key', name=op.f('uq_document_chunks_chunk_key'))
    )
    op.create_index(op.f('ix_document_chunks_canonical_document_id'), 'document_chunks', ['canonical_document_id'], unique=False)
    op.create_index('ix_document_chunks_document_status', 'document_chunks', ['canonical_document_id', 'index_status'], unique=False)
    op.create_index(op.f('ix_document_chunks_index_status'), 'document_chunks', ['index_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_index_status'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_status', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_canonical_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_canonical_documents_content_hash'), table_name='canonical_documents')
    op.drop_table('canonical_documents')
    op.drop_index(op.f('ix_file_metadata_connector_id'), table_name='file_metadata')
    op.drop_table('file_metadata')
    op.drop_index(op.f('ix_connectors_status'), table_name='connectors')
    op.drop_table('connectors')
    # ### end Alembic commands ###
